### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by JanMikes** [WebChemistry/images#12]
Info about how to change checkbox's label "Delete this image?" would be nice.

This is what i tried and didnt work for me:

``` php
$image = $form->addImageUpload("image", "image")
            ->setDefaultValue($entity->getImage());

        $checkbox = $image->getCheckbox();
        $checkbox::$labelContent = "test";
```

If i do this: `Checkbox::$labelContent = "test";` before adding input, it works. Though what is the best place to globally change this value for all inputs, bootstrap.php?

**Comment by JanMikes** [comment]
Neither this is working for me:

``` php
$image->getCheckbox()->getLabelPart()->setHtml("test");
```

**Comment by MartkCz** [comment]
I think it must works:

``` php
$image->getCheckbox()->caption = "foo";
```

Checkbox::$labelContent is only for global use, for example in bootstrap

**Comment by JanMikes** [comment]
@MartkCz this works thanks.
Anyways i wanted to use the global variant and as you mentioned i am using it in bootstrap.php.
Though in previous versions there was possibility to to change caption globally in extensions settings, what do you think about putting it back, since i think static access to property is not so clean.

**Comment by JanMikes** [comment]
Awesome, thank you!
