### ISSUE TITLE
A mistake in docu

### ISSUE THREAD

**Issue by igorpocta2** [WebChemistry/images#14]
There is a mistake in the documentation.

```
extensions:
    images: WebChemistry\Images\DI\ImagesExtension
```

Correct is **Extension**, because in the file you have got these lines:

_<?php
namespace WebChemistry\Images\DI;
use Nette;
use WebChemistry\Images\ImageStorageException;
class Extension extends Nette\DI\CompilerExtension {_

**Comment by MartkCz** [comment]
I have master branch as default. This branch contains features, BC breaks and this is one of them, because I want release version 2.2 soon. 

Branch [2.1 is here](https://github.com/WebChemistry/images/tree/v2.1)
