### ISSUE TITLE
DigitalOcean Spaces with CDN

### ISSUE THREAD

**Issue by Bezdekm** [WebChemistry/images#32]
Hello,
I would like to use it in my projects with DO Spaces (AWS S3 compatible). With standard origin endpoint is is perfectly working, but i need to get it works with CDN endpoint. Is here any way to transform url of getting image? Something from xxx.ams3.digxxx to xxx.ams3.cdn.digixxx?

PS: It is possible to set root (or default namespace prefix)?

Thanks.

**Comment by krekos** [comment]
1st Q:  You can't now. But I looked to code (and to some tutorials about AWS and DO)  and I think it shouldn't be too hard to add this feature. Just few lines of code. So you can try add it and then send it as a PR. 

2nd Q: I work wth S3 only for short time. So i don't know much about namespaces. When i was creating S3 extension I only needed basic support. So answer to your question is pobbably no.

**Comment by Bezdekm** [comment]
https://github.com/WebChemistry/images/pull/33
