### ISSUE TITLE
How to get width and height of the resource?

### ISSUE THREAD

**Issue by vylink** [WebChemistry/images#35]
Hi,

is there any way of how to get image size (width and height) from the resource?

This is what I was using previously: 
```
$bigImage->getNetteImageClass()->getWidth();
```

Bellow you can find a snippet of my current code:
```
$resource = $this->imageStorage->createResource('news/' . $dbImage->id . "-" . $dbImage->name);
$bigImage = $this->imageStorage->link($resource);

// how can I get width and height of the $bigImage here?

```

Cheers

**Comment by krekos** [comment]
If you using LocalStorage you can do this:

$imgSize = $this->imageStorage->getImageSize($resource);
$imgSize->getWidth();
$imgSize->getHeight();

**Comment by vylink** [comment]
Fantastic. Thank you.
