### ISSUE TITLE
fixOrientation modifier on FileResource

### ISSUE THREAD

**Issue by martenb** [WebChemistry/images#42]
Hello,
I need fixOrientation modifier on FileResource, but it is only for ITransferResource. 

I tried to create custom ModifiersLoader, but i don't know, how to get IImageStorage to get path to file for exif_read_data... I tried to inject it, but it fails with

`Circular reference detected for services: images.template.facade, images.storage, images.resourceMetaFactory, images.modifiers.`

Thx for help...

**Comment by MartkCz** [comment]
You should call fixOrientation only if new image is uploaded. When image is saved, exif data are destroyed (gd library doesn't store exif data), so modifier fixOrientation on FileResource has no effect.

**Comment by martenb** [comment]
I store original photos from upload, so I have exif on saved images.

**Comment by MartkCz** [comment]
try dev-master, please

**Comment by martenb** [comment]
I cannot test it, because dev-master requires nette/http:^3.0, I am on 2.4...

**Comment by MartkCz** [comment]
So try 4.1.5, please

**Comment by martenb** [comment]
Not working, function exits on 

https://github.com/WebChemistry/images/blob/4.1.5/src/Modifiers/BaseModifiers.php#L43

**Comment by MartkCz** [comment]
4.1.6

**Comment by martenb** [comment]
Works well, thank you. I prepared merge request with more complex fixOrientation. #43
