### ISSUE TITLE
nette/forms v3.0.3 compatibility

### ISSUE THREAD

**Issue by becygroup** [WebChemistry/images#44]
With the latest version of nette/forms (v3.0.3) is not possible use `\WebChemistry\Images\Controls\AdvancedUploadControl`. It throws error: `Call to undefined method WebChemistry\Images\Resources\StateResource::getSize()` because of this change: https://github.com/nette/forms/commit/69fb18e37f350b21125b223e40f1ab034561b9ed (automatically sets rule :fileSize according PHP setting).

How can I help with fix this?

**Comment by MartkCz** [comment]
Can you try dev-master, please?

**Comment by becygroup** [comment]
Yes, It works for me. Thank you for your fast solution :-)
